#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 28 22:16:24 2022

@author: nico
"""
d_iso3 = {'England': 'GBR',
 'Portugal': 'PRT',
 'Spain': 'ESP',
 'United States': 'USA',
 'Canada': 'CAN',
 'Sweden': 'SWE',
 'Italy': 'ITA',
 'France': 'FRA',
 'Belgium': 'BEL',
 'Australia': 'AUS',
 'Germany': 'DEU',
 'Netherlands': 'NLD',
 'Israel': 'ISR',
 'Switzerland': 'CHE',
 'Greece': 'GRC',
 'Austria': 'AUT',
 'Argentina': 'ARG',
 'Denmark': 'DNK',
 'Morocco': 'MAR',
 'Slovenia': 'SVN',
 'Scotland': 'GBR',
 'Czech Republic': 'CZE',
 'United Arab Emirates': 'ARE',
 'Finland': 'FIN',
 'Wales': 'GBR',
 'Northern Ireland': 'GBR',
 'Sudan': 'SDN',
 'Bolivia': 'BOL',
 'Iran': 'IRN',
 'Ecuador': 'ECU',
 'Malta': 'MLT',
 'Ireland': 'IRL',
 'Mexico': 'MEX',
 'Pakistan': 'PAK',
 'French Guiana': 'GUF',
 'Thailand': 'THA',
 'Peru': 'PER',
 'Brazil': 'BRA',
 'Malaysia': 'MYS',
 'Hungary': 'HUN',
 'Norway': 'NOR',
 'Paraguay': 'PRY',
 'Costa Rica': 'CRI',
 'Gibraltar': 'GIB',
 'Mauritius': 'MUS',
 'Haiti': 'HTI',
 'Uruguay': 'URY',
 'Latvia': 'LVA',
 'Cayman Islands': 'CYM',
 'Kosovo': 'SRB',
 'Turkey': 'TUR',
 'Bahamas': 'BHS',
 'Ghana': 'GHA',
 'India': 'IND',
 'Iceland': 'ISL',
 'Poland': 'POL',
 'Bangladesh': 'BGD',
 'Uganda': 'UGA',
 'Cambodia': 'KHM',
 'Malawi': 'MWI',
 'Venezuela': 'VEN',
 'Romania': 'ROU',
 'Georgia': 'GEO',
 'Slovakia': 'SVK',
 'Luxembourg': 'LUX',
 'Nepal': 'NPL',
 'Chile': 'CHL',
 'Serbia': 'SRB',
 'Lebanon': 'LBN',
 'South Korea': 'KOR',
 'Singapore': 'SGP',
 'South Africa': 'ZAF',
 'Taiwan': 'TWN',
 'Colombia': 'COL',
 'Croatia': 'HRV',
 'Bulgaria': 'BGR',
 'Somalia': 'SOM',
 'Zambia': 'ZMB',
 'Fiji': 'FJI',
 'Benin': 'BEN',
 'Estonia': 'EST',
 'Puerto Rico': 'PRI',
 'Panama': 'PAN',
 'Dominican Republic': 'DOM',
 'Jamaica': 'JAM',
 'New Zealand': 'NZL',
 'Russia': 'RUS',
 'Bosnia And Herzegovina': 'BIH',
 'Saudi Arabia': 'SAU',
 'Martinique': 'FRA',
 'Barbados': 'BRB',
 'Qatar': 'QAT',
 'Bermuda': 'BMU',
 'Japan': 'JPN',
 'Guadeloupe': 'FRA',
 'Andorra': 'AND',
 'New Caledonia': 'NCL',
 'China': 'CHN',
 'Philippines': 'PHL',
 'Montenegro': 'MNE',
 'Cyprus': 'CYP',
 'Lithuania': 'LTU',
 'Guatemala': 'GTM',
 'Saint Martin (French part)': 'MAF',
 'Greenland': 'GRL',
 'Moldova': 'MDA',
 'Honduras': 'HND',
 'Monaco': 'MCO',
 'Indonesia': 'IDN',
 'Curaçao': 'CUW',
 'Aruba': 'ABW',
 'Cuba': 'CUB',
 'Guyana': 'GUY',
 'El Salvador': 'SLV',
 'Belize': 'BLZ',
 'Hong Kong': 'HKG',
 'South Sudan': 'SSD',
 'Egypt': 'EGY',
 'Jordan': 'JOR',
 'Guam': 'GUM',
 'Ukraine': 'UKR',
 'Nigeria': 'NGA',
 'Democratic Republic Of The Congo': 'COD',
 'Central African Republic': 'CAF',
 'Republic of Congo': 'COG',
 'Cameroon': 'CMR',
 'Liberia': 'LBR',
 'Sierra Leone': 'SLE'}